site_name: Huezoo
site_url: https://ksharma-xyz.github.io/Huezoo/
site_author: ksharma-xyz
site_description: A color-matching game for curious minds.

repo_name: ksharma-xyz/Huezoo
repo_url: https://github.com/ksharma-xyz/Huezoo
edit_uri: ""

theme:
  name: material
  custom_dir: overrides
  favicon: assets/huezoo-icon.png
  logo: assets/huezoo-icon.png
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  font:
    text: Space Grotesk
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Privacy Policy: privacy-policy.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ksharma-xyz
  generator: false

copyright: Copyright &copy; 2025 ksharma-xyz
